#!/bin/bash

echo "🚀 Auto Domain & SSL Test"
echo "================================"

PROJECT_NAME="auto-domain-test"
API_URL="http://141.164.60.51:3007/api"

echo "📦 Project: $PROJECT_NAME"
echo "🌐 Domain: $PROJECT_NAME.one-q.xyz (auto-generated)"
echo "🔒 SSL: Let's Encrypt (automatic)"
echo ""

# 자동 도메인 생성으로 배포
echo "Creating application with auto domain..."
curl -X POST "$API_URL/deploy/complete" \
  -H "Content-Type: application/json" \
  -d '{
    "projectName": "'$PROJECT_NAME'",
    "gitRepository": "https://github.com/coollabsio/coolify-examples",
    "gitBranch": "main",
    "buildPack": "nixpacks",
    "port": "3000",
    "generateDomain": true,
    "databases": [
      {"type": "postgresql", "name": "db"}
    ],
    "environmentVariables": [
      {"key": "NODE_ENV", "value": "production"}
    ]
  }' | jq .

echo ""
echo "================================"
echo "✅ Deployment completed!"
echo ""
echo "Domain will be available at:"
echo "  🌐 https://$PROJECT_NAME.one-q.xyz"
echo "  📊 Dashboard: http://141.164.60.51:8000/projects"
echo ""
echo "SSL certificate will be automatically generated by Let's Encrypt"