#!/bin/bash
# CodeB Quadlet Deployment Script
# 3-Layer Architecture: Delivery Layer
#
# Usage:
#   ./deploy-quadlet.sh [project-name] [environment] [image-tag]
#
# Examples:
#   ./deploy-quadlet.sh my-app staging latest
#   ./deploy-quadlet.sh my-app production v1.2.3

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }

# Arguments
PROJECT_NAME="${1:-codeb-app}"
ENVIRONMENT="${2:-staging}"
IMAGE_TAG="${3:-latest}"

# Configuration
REGISTRY="${REGISTRY:-ghcr.io}"
ORG="${GITHUB_REPOSITORY_OWNER:-codeblabdev-max}"
IMAGE="${REGISTRY}/${ORG}/${PROJECT_NAME}:${IMAGE_TAG}"

QUADLET_DIR="/etc/containers/systemd"
CONFIG_DIR="/opt/codeb"
ENV_FILE="${CONFIG_DIR}/envs/${ENVIRONMENT}.env"

# Port allocation based on environment
case "$ENVIRONMENT" in
  production) PORT=3000 ;;
  staging)    PORT=3001 ;;
  preview)    PORT=3002 ;;
  *)          PORT=3000 ;;
esac

log "=== CodeB Quadlet Deployment ==="
log "Project: ${PROJECT_NAME}"
log "Environment: ${ENVIRONMENT}"
log "Image: ${IMAGE}"
log "Port: ${PORT}"

# Pre-flight checks
log "Running pre-flight checks..."

# Check Podman
if ! command -v podman &> /dev/null; then
  error "Podman not found. Install Podman 4.4+ first."
fi

PODMAN_VERSION=$(podman --version | grep -oP '\d+\.\d+')
log "Podman version: ${PODMAN_VERSION}"

# Check Quadlet
if [ ! -f "/usr/libexec/podman/quadlet" ]; then
  error "Quadlet not found. Requires Podman 4.4+"
fi
success "Quadlet available"

# Ensure directories exist
log "Creating directories..."
sudo mkdir -p ${CONFIG_DIR}/{config,data,logs,envs,backup}
sudo mkdir -p ${CONFIG_DIR}/data/${PROJECT_NAME}
sudo mkdir -p ${CONFIG_DIR}/logs/${PROJECT_NAME}

# Create env file if not exists
if [ ! -f "${ENV_FILE}" ]; then
  warn "Environment file not found: ${ENV_FILE}"
  log "Creating template..."
  sudo tee "${ENV_FILE}" > /dev/null << EOF
# ${PROJECT_NAME} - ${ENVIRONMENT} Environment
NODE_ENV=${ENVIRONMENT}
PORT=3000
# DATABASE_URL=postgresql://user:pass@codeb-postgres:5432/${PROJECT_NAME}
# REDIS_URL=redis://codeb-redis:6379
EOF
  warn "Please edit ${ENV_FILE} with your configuration"
fi

# Login to registry (if GHCR token available)
if [ -n "${GHCR_TOKEN:-}" ]; then
  log "Logging into GHCR..."
  echo "${GHCR_TOKEN}" | podman login ghcr.io -u "${GITHUB_ACTOR:-codeb}" --password-stdin
  success "GHCR login successful"
else
  warn "GHCR_TOKEN not set. Assuming public image or pre-authenticated."
fi

# Pull image
log "Pulling image: ${IMAGE}"
if podman pull "${IMAGE}"; then
  success "Image pulled successfully"
else
  error "Failed to pull image: ${IMAGE}"
fi

# Backup current container (if exists)
if podman container exists "${PROJECT_NAME}"; then
  log "Backing up current container..."
  BACKUP_TAG="backup-$(date +%Y%m%d-%H%M%S)"
  podman commit "${PROJECT_NAME}" "${PROJECT_NAME}:${BACKUP_TAG}" 2>/dev/null || true
  success "Backup created: ${PROJECT_NAME}:${BACKUP_TAG}"
fi

# Generate Quadlet container file
log "Generating Quadlet configuration..."
CONTAINER_FILE="${QUADLET_DIR}/${PROJECT_NAME}.container"

sudo tee "${CONTAINER_FILE}" > /dev/null << EOF
# Auto-generated by deploy-quadlet.sh
# Project: ${PROJECT_NAME}
# Environment: ${ENVIRONMENT}
# Generated: $(date -Iseconds)

[Unit]
Description=${PROJECT_NAME} (${ENVIRONMENT})
Documentation=https://github.com/${ORG}/${PROJECT_NAME}
After=network-online.target
Wants=network-online.target

[Container]
Image=${IMAGE}
ContainerName=${PROJECT_NAME}
PublishPort=${PORT}:3000
Environment=NODE_ENV=${ENVIRONMENT}
EnvironmentFile=${ENV_FILE}
Volume=${CONFIG_DIR}/data/${PROJECT_NAME}:/app/data:Z
Volume=${CONFIG_DIR}/logs/${PROJECT_NAME}:/app/logs:Z
Network=codeb
Label=codeb.project=${PROJECT_NAME}
Label=codeb.environment=${ENVIRONMENT}
Label=codeb.deployed=$(date -Iseconds)

# Health check
HealthCmd=/usr/bin/curl -sf http://localhost:3000/health || exit 1
HealthInterval=30s
HealthTimeout=10s
HealthRetries=3
HealthStartPeriod=60s

# Security
NoNewPrivileges=true

[Service]
Restart=always
RestartSec=10s
TimeoutStartSec=300
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target default.target
EOF

success "Quadlet file created: ${CONTAINER_FILE}"

# Reload systemd
log "Reloading systemd daemon..."
sudo systemctl daemon-reload
success "systemd daemon reloaded"

# Restart service
SERVICE_NAME="${PROJECT_NAME}.service"
log "Restarting service: ${SERVICE_NAME}"

if sudo systemctl is-active --quiet "${SERVICE_NAME}"; then
  sudo systemctl restart "${SERVICE_NAME}"
else
  sudo systemctl enable --now "${SERVICE_NAME}"
fi

# Wait for service to start
log "Waiting for service to start..."
sleep 5

# Health check loop
log "Running health checks..."
MAX_RETRIES=12
RETRY_INTERVAL=5

for i in $(seq 1 $MAX_RETRIES); do
  if curl -sf "http://localhost:${PORT}/health" > /dev/null 2>&1; then
    success "Health check passed!"
    break
  fi

  if [ $i -eq $MAX_RETRIES ]; then
    warn "Health check not passing after ${MAX_RETRIES} attempts"
    warn "Service may still be starting. Check: journalctl -u ${SERVICE_NAME} -f"
  else
    log "Waiting for app to be healthy... (${i}/${MAX_RETRIES})"
    sleep $RETRY_INTERVAL
  fi
done

# Show service status
log "Service status:"
sudo systemctl status "${SERVICE_NAME}" --no-pager || true

# Summary
echo ""
log "=== Deployment Summary ==="
success "Project: ${PROJECT_NAME}"
success "Environment: ${ENVIRONMENT}"
success "Image: ${IMAGE}"
success "Port: ${PORT}"
success "Service: ${SERVICE_NAME}"
success "Quadlet: ${CONTAINER_FILE}"
success "Env file: ${ENV_FILE}"
echo ""
log "Useful commands:"
echo "  - Status:  sudo systemctl status ${SERVICE_NAME}"
echo "  - Logs:    journalctl -u ${SERVICE_NAME} -f"
echo "  - Restart: sudo systemctl restart ${SERVICE_NAME}"
echo "  - Stop:    sudo systemctl stop ${SERVICE_NAME}"
echo ""
success "Deployment complete!"
